development:
  adapter: mysql2
  database: iamanu
  pool: 5
  username: root  
  password: root
  host: localhost
  port: 5432

production:
  adapter: mysql2
  database: iamanu
  pool: 5
  username: root  
  password: root
  host: localhost
  port: 5432  